# Generated by Django 3.2.10 on 2022-09-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_auto_20220922_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='plataform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplataform'),
            preserve_default=False,
        ),
    ]
